name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: add credential
      run: echo "https://x-access-token:${{ secrets.Bibucket_Token }}@bitbucket.org" >> ~/.git-credentials
    - name: Checkout private tools
      run: git clone https://agam_mahajan:${{ secrets.Bibucket_Token }}@bitbucket.org/swigy/swiggy-ios.git
    - name: Install Dependencies
      run:  pod install
    - name: Build And Run Tests
      run:  xcodebuild -workspace SwiftExample.xcworkspace -scheme SwiftExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4.1' build test
