name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
      repository: https://github.com/swiggy-private/ios-home-protobuf
      token: ${{ secrets.Bibucket_Token }}
    - name: Install Dependencies
      run:  pod install
    - name: Build And Run Tests
      run:  xcodebuild -workspace SwiftExample.xcworkspace -scheme SwiftExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4.1' build test
